#!/usr/bin/env bash
#
# Smoke — Host-side setup script
#
# Run this from your project root (where .ddev/ lives):
#   bash web/modules/contrib/smoke/scripts/host-setup.sh
#
# This script:
#   1. Verifies DDEV is running
#   2. Installs npm dependencies inside the container
#   3. Installs Chromium browser + system deps (one-time)
#   4. Installs a DDEV post-start hook for auto-config
#   5. Runs drush smoke:setup to finish configuration
#
# No third-party DDEV addons required.
#
set -euo pipefail

BOLD='\033[1m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m'

step()  { echo -e "  ${BLUE}▸${NC} $1"; }
ok()    { echo -e "    ${GREEN}✓${NC} $1"; }
warn()  { echo -e "    ${YELLOW}⚠${NC} $1"; }
fail()  { echo -e "    ${RED}✕${NC} $1"; exit 1; }

echo ""
echo -e "  ${BOLD}Smoke — Full Setup${NC}"
echo "  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# ── Step 1: Verify DDEV project ──
step "Checking for DDEV project..."
if [ ! -d ".ddev" ]; then
  fail "No .ddev/ directory found. Run this from your project root."
fi
ok "DDEV project found."

# Check DDEV is running.
step "Checking DDEV is running..."
if ! ddev describe > /dev/null 2>&1; then
  echo "    Starting DDEV..."
  ddev start
fi
ok "DDEV is running."

# ── Step 2: Resolve Smoke module's playwright directory ──
step "Locating Smoke module..."
SMOKE_PW_DIR=$(ddev exec drush eval "echo DRUPAL_ROOT . '/' . \Drupal::service('extension.list.module')->getPath('smoke') . '/playwright';" 2>/dev/null || echo "")

if [ -z "$SMOKE_PW_DIR" ]; then
  # Fallback: common paths.
  for candidate in "web/modules/contrib/smoke/playwright" "web/modules/custom/smoke/playwright" "docroot/modules/contrib/smoke/playwright"; do
    if ddev exec "test -d /var/www/html/$candidate" 2>/dev/null; then
      SMOKE_PW_DIR="/var/www/html/$candidate"
      break
    fi
  done
fi

if [ -z "$SMOKE_PW_DIR" ]; then
  fail "Could not find the Smoke module. Is it installed? (composer require drupal/smoke)"
fi
ok "Found: $SMOKE_PW_DIR"

# ── Step 3: Install npm dependencies ──
step "Installing npm dependencies..."
ddev exec "cd $SMOKE_PW_DIR && npm install"
ok "Dependencies installed."

# ── Step 4: Install Chromium browser + system deps ──
step "Checking for Chromium browser..."
BROWSER_INSTALLED=$(ddev exec "ls -d \$HOME/.cache/ms-playwright/chromium-* 2>/dev/null | head -1" || echo "")

if [ -n "$BROWSER_INSTALLED" ]; then
  ok "Chromium already installed."
else
  step "Installing Chromium browser (~180 MiB one-time download)..."
  ddev exec "cd $SMOKE_PW_DIR && npx playwright install chromium"
  ok "Chromium installed."
fi

step "Ensuring system dependencies..."
ddev exec "sudo npx playwright install-deps chromium 2>&1 | tail -3"
ok "System dependencies ready."

# ── Step 5: Install DDEV post-start hook ──
step "Installing DDEV post-start hook..."
HOOK_FILE=".ddev/config.smoke.yaml"
if [ -f "$HOOK_FILE" ]; then
  ok "DDEV hook already installed."
else
  cat > "$HOOK_FILE" <<'HOOKEOF'
# Auto-generated by Smoke module setup.
# Regenerates Smoke test config on every ddev start/restart.
hooks:
  post-start:
    - exec: drush smoke:setup --silent 2>/dev/null || true
HOOKEOF
  ok "DDEV hook installed — config auto-regenerates on ddev start."
fi

# ── Step 6: Run Drush setup ──
step "Running drush smoke:setup..."
echo ""
ddev drush smoke:setup
